version: '3.3'
services:
    ethereum:
        hostname: ethereum
        image: ethereum/client-go:alpine
        ports:
            - "127.0.0.1:8545:8545"
        volumes:
            - ./ethereum:/root/.ethereum
        command: --fast --cache=2048 --rpc --rpcaddr "127.0.0.1" --unlock 0x533FB5E587c651852fee15b1588cD71934af0933  --password /root/.ethereum/keystore/password  --verbosity 1 

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass

    database:
        hostname: database
        image: redis:latest
        volumes:
            - ./redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always

    server:
        hostname: server
        build:
            context: .
            dockerfile: server_dockerfile
        environment:
            - ETH_RPC_PORT=8545
            - RPC_PORT=7080
            - ZEEW_TX_MINING_TIME=5
        ports:
            - "127.0.0.1:7080:7080"
        links:
            - rabbit
        depends_on:
            - rabbit
            - ethereum

    worker:
        build:
            context: .
            dockerfile: worker_dockerfile
        environment:
            - THREADING_BACKEND=gevent
            - CONTRACT_ADDR=0x6278ae7b2954ba53925EA940165214da30AFa261
            - ETH_RPC_PORT=8545
            - ETH_HOST=ethereum
            - INVESTMENT_HOST=127.0.0.1
            - INVESTMENT_RPC_PORT=7081
        links:
            - rabbit
            - database
        depends_on:
            - rabbit
            - database
            - ethereum
