version: '3.3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
#       environment:
#           - RABBITMQ_DEFAULT_USER=admin
#           - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    database:
        hostname: database
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always

    server:
        hostname: server
        build:
            context: .
            dockerfile: server_dockerfile
        environment:
            - ETH_RPC_PORT=8545
            - RPC_PORT=7080
        ports:
            - "7080:7080"
        links:
            - rabbit
        depends_on:
            - rabbit

    worker:
        build:
            context: .
            dockerfile: worker_dockerfile
        volumes:
            - .:/app
        environment:
            - THREADING_BACKEND=gevent
            - CONTRACT_ADDR=0x6278ae7b2954ba53925EA940165214da30AFa261
            - ETH_RPC_PORT=8545
            - ETH_HOST=192.168.0.45
            - ZEEW_TX_MINING_TIME=1
            - SAVE_RESULTS_TO_DB=1
            - INVESTMENT_HOST=192.168.0.45
        links:
            - rabbit
            - database
        depends_on:
            - rabbit
            - database

    flower:
        hostname: flower
        image: totem/celery-flower-docker
        environment:
            - AMQP_HOST=rabbit
            - AMQP_USERNAME=admin
            - AMQP_PASSWORD=mypass
        ports:
             - "5555:5555"
        entrypoint: flower
        links:
            - rabbit
        depends_on:
            - rabbit
