version: '3.3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27018:27017"

#   ethereum:
#       hostname: ethereum
#       image: ethereum/client-go:alpine
#       ports:
#           - "30303:30303"
#           - "8545:8545"
#       volumes:
#           - ./ethereum:/root/.ethereum
#       command: --rpc --rpcaddr "0.0.0.0"

    worker:
        build:
            context: .
            dockerfile: dockerfile
        deploy:
            replicas: 4
        environment:
            THREADING_BACKEND=gevent
            CONTRACT_ADDR=0x6278ae7b2954ba53925ea940165214da30afa261
            ETH_RPC_PORT=8545
            RPC_PORT=7080
        volumes:
            - .:/app
        links:
            - rabbit
            - database
#           - ethereum
        depends_on:
            - rabbit
            - database
#           - ethereum
