version: '3.3'
services:
    ethereum:
        hostname: ethereum
        image: ethereum/client-go:alpine
        ports:
            - "30303:30303"
            - "8545:8545"
        volumes:
            - ./ethereum:/root/.ethereum
        command: --light --rpc --unlock 0 --password /root/.ethereum/keystore/password  # --verbosity 1
