version: '3.3'
services:
    geth:
        hostname: geth
        image: ethereum/client-go:alpine
        command: --light

    ethereum:
        hostname: ethereum
        image: parity/parity:latest
        container_name: parity_container
        volumes:
            - ./ethereum:/root/.local/share/io.parity.ethereum
        working_dir: /parity/
        command: --chain=ropsten --jsonrpc-interface '0.0.0.0'  --unlock 0x21e66e44BCCD87c3f3a598bc1f14e2353D0ace72  --password /root/.local/share/io.parity.ethereum/keys/ethereum/password

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        restart: always

    database:
        hostname: database
        image: redis:latest
        volumes:
            - ./redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always

    server:
        hostname: server
        build:
            context: .
            dockerfile: test_server_dockerfile
        volumes:
            - .:/app
        environment:
            - ETH_RPC_PORT=8545
            - RPC_PORT=7080
            - ZEEW_TX_MINING_TIME=2
            - TIME_ZONE=Europe/Moscow
        ports:
            - "127.0.0.1:7080:7080"
        depends_on:
            - rabbit
            - ethereum

    worker:
        build:
            context: .
            dockerfile: test_worker_dockerfile
        volumes:
            - .:/app
        environment:
            - THREADING_BACKEND=gevent
            - HOLDER_CONTRACT_ADDR=0x6278ae7b2954ba53925EA940165214da30AFa261
            - CROWDSALE_CONTRACT_ADDR=0xF4aa8b2a7b1c66CacC185AA4499f0B27D82633D3
            - ETH_RPC_PORT=8545
            - ETH_HOST=ethereum
              # don't set 127.0.0.1 here, use docker's bridge iface
            - INVESTMENT_HOST=172.18.0.1
            - INVESTMENT_RPC_PORT=7081
            - GAS_LIMIT=200000
            - GAS_PRICE=41
        depends_on:
            - rabbit
            - database
            - ethereum

    flower:
        hostname: flower
        image: totem/celery-flower-docker
        environment:
            - AMQP_HOST=rabbit
            - AMQP_USERNAME=admin
            - AMQP_PASSWORD=mypass
        ports:
            - "127.0.0.1:5555:5555"
        entrypoint: flower
        depends_on:
            - worker
            - rabbit
