version: '3.3'
services:
    ethereum:
        hostname: ethereum
        image: ethereum/client-go:alpine
        ports:
            - "30303:30303"
            - "8545:8545"
        volumes:
            - ./ethereum:/root/.ethereum
        command: --rpc --rpcaddr "0.0.0.0" --unlock 0x533FB5E587c651852fee15b1588cD71934af0933  --password /root/.ethereum/keystore/password  --verbosity 1

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    database:
        hostname: database
        image: redis:latest
        volumes:
            - ./redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always

    server:
        hostname: server
        build:
            context: .
            dockerfile: test_server_dockerfile
        volumes:
            - .:/app
        environment:
            - ETH_RPC_PORT=8545
            - RPC_PORT=7080
            - ZEEW_TX_MINING_TIME=1
        ports:
            - "7080:7080"
        links:
            - rabbit
        depends_on:
            - rabbit
            - ethereum

    worker:
        build:
            context: .
            dockerfile: test_worker_dockerfile
        volumes:
            - .:/app
        environment:
            - THREADING_BACKEND=gevent
            - CONTRACT_ADDR=0x6278ae7b2954ba53925EA940165214da30AFa261
            - ETH_RPC_PORT=8545
            - ETH_HOST=192.168.0.45
            - INVESTMENT_HOST=192.168.0.45
            - INVESTMENT_RPC_PORT=7081
        links:
            - rabbit
            - database
        depends_on:
            - rabbit
            - database
            - ethereum

    flower:
        hostname: flower
        image: totem/celery-flower-docker
        environment:
            - AMQP_HOST=rabbit
            - AMQP_USERNAME=admin
            - AMQP_PASSWORD=mypass
        ports:
             - "5555:5555"
        entrypoint: flower
        links:
            - rabbit
        depends_on:
            - worker
